name: Issue Template
description: Template to capture issue information
title: titulo de la issue
labels: label
assignees: asignados

body:
  - type: input
    id: name
    attributes:
      label: Name
      description: Enter your name
      placeholder: Your name

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Enter the description
      placeholder: Description

  - type: input
    id: email
    attributes:
      label: Email
      description: Enter your email
      placeholder: Your email

  - type: dropdown
    id: action
    attributes:
      label:  
      description: Accion a realizar
      options:
        - new entity
        - update entity
        - universe change
        - optimization
    validations:
      required: true

  - type: dropdown
    id: entity
    attributes:
      label: Entidad
      description: Entidad impactada por la optimización
      options:
        - account
        - bankwithdrawals
        - bureaus
        - ccardaggpercat
        - contactcollection
        - coronavaucher
        - creditcard
        - credits
        - devices
        - flags
        - funding
        - merchantsbehavior
        - names
        - navigation
        - notifications
        - payments
        - prepaid
        - sellerclassification
        - sellers
        - shipments
        - sociodemographic
        - userpix
    validations:
      required: true

  - type: input
    id: feature
    attributes:
      label: Feature to Modify
      description: Enter the feature to modify
      placeholder: Feature

  - type: textarea
    id: queries
    attributes:
      label: List of Queries
      description: Enter the list of queries
      placeholder: Queries
