name: Create Issue from PR

on:
  pull_request:
    types: [opened,edited]

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Extract PR data
      id: extract_data
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        PR_BODY="${{ github.event.pull_request.body }}"
        echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV
        echo "PR_BODY=$PR_BODY" >> $GITHUB_ENV

    - name: Create Issue
      run: |
        gh auth login --with-token <<< "${{ secrets.REPO_SECRET }}"
        gh issue create --title "$PR_TITLE" --body "$PR_BODY"
