name: Create PR from Form

on:
  issues:
    types: [opened]

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Create new branch
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git checkout -b form-submission-${{ github.event.issue.number }}

    - name: Create SQL query file
      run: |
        echo "${{ github.event.issue.body }}" > query.sql

    - name: Commit changes
      run: |
        echo "Committing changes to form-submission-${{ github.event.issue.number }}"

    - name: Push changes
      run: |
        echo "Pushing changes to form-submission-${{ github.event.issue.number }}"

    - name: Create Pull Request
      run: |
        echo "Creating pull request for form submission #${{ github.event.issue.number }}"
